import { useEffect, useState } from 'react';
import { Activity, ArrowLeft, Check, ChevronRight, Coffee, Flame, Heart, History, Info, Pause, Play, RotateCcw, Settings, Smartphone, Sparkles, Timer, X } from 'lucide-react';
import { generateNudge } from './ai/nudge';

type Session = { id: string; task: string; minutes: number; date: string; reflection: string; away: number; urge: number; phoneDown?: boolean };
type Data = { sessions: Session[]; totalAway: number; totalUrges: number };
const EMPTY: Data = { sessions: [], totalAway: 0, totalUrges: 0 };
const load = (): Data => { try { return { ...EMPTY, ...JSON.parse(localStorage.getItem('fb-data') || '{}') }; } catch { return EMPTY; } };
const fmt = (n: number) => `${String(Math.floor(n / 60)).padStart(2,'0')}:${String(n % 60).padStart(2,'0')}`;
const dayKey = (d: Date) => d.toISOString().slice(0, 10);
const dateLabel = (d: string) => { const x = new Date(d); return dayKey(x) === dayKey(new Date()) ? 'Today' : x.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric' }); };

export default function App() {
  const [data, setData] = useState<Data>(load), [screen, setScreen] = useState('home'), [task, setTask] = useState(''), [taskInput, setTaskInput] = useState(''), [duration, setDuration] = useState(25), [remaining, setRemaining] = useState(0), [running, setRunning] = useState(false), [kind, setKind] = useState<'starter'|'focus'|'break'>('focus'), [away, setAway] = useState(0), [urge, setUrge] = useState(0), [urgeLeft, setUrgeLeft] = useState(60), [reflection, setReflection] = useState(''), [nudge, setNudge] = useState(''), [aiLabel, setAiLabel] = useState(''), [phoneModal, setPhoneModal] = useState(false), [installPrompt, setInstallPrompt] = useState<any>(null), [installable, setInstallable] = useState(false), [about, setAbout] = useState(false);
  const save = (next: Data) => { setData(next); localStorage.setItem('fb-data', JSON.stringify(next)); };
  useEffect(() => { const h = (e: Event) => { e.preventDefault(); setInstallPrompt(e); setInstallable(true); }; window.addEventListener('beforeinstallprompt', h); return () => window.removeEventListener('beforeinstallprompt', h); }, []);
  useEffect(() => { if (!running) return; const id = window.setInterval(() => setRemaining(n => { if (n <= 1) { setRunning(false); if (kind === 'break') setScreen('home'); else { setScreen('complete'); setPhoneModal(true); } return 0; } return n - 1; }), 1000); return () => clearInterval(id); }, [running, kind]);
  useEffect(() => { if (screen !== 'urge') return; const id = window.setInterval(() => setUrgeLeft(n => { if (n <= 1) { clearInterval(id); return 0; } return n - 1; }), 1000); return () => clearInterval(id); }, [screen]);
  useEffect(() => { const fn = () => { if (document.hidden && running && kind !== 'break') { setAway(n => n + 1); save({ ...data, totalAway: data.totalAway + 1 }); } }; document.addEventListener('visibilitychange', fn); return () => document.removeEventListener('visibilitychange', fn); }, [running, kind, data]);
  const startForm = () => { setTaskInput(task); setScreen('setup'); };
  const begin = async (mins: number, type: 'starter'|'focus'|'break') => { const goal = type === 'starter' ? 2 : mins; setTask(taskInput.trim() || 'A little focused work'); setKind(type); setDuration(goal); setRemaining(goal * 60); setAway(0); setUrge(0); setNudge(''); setScreen(type === 'break' ? 'timer' : 'timer'); setRunning(true); setPhoneModal(type !== 'break'); if (type !== 'break') { const res = await generateNudge({ task: taskInput.trim() || 'A little focused work', minutes: goal, distractions: data.totalAway, reflections: data.sessions.map(s => s.reflection).filter(Boolean) }, s => setAiLabel(s)); setNudge(res.text); setAiLabel(res.localModel ? 'Generated on this device with Qwen' : 'A small local nudge'); } };
  const finish = (phoneDown?: boolean, text = reflection) => { const s: Session = { id: crypto.randomUUID(), task, minutes: kind === 'starter' ? 2 : duration, date: new Date().toISOString(), reflection: text.trim(), away, urge, phoneDown }; save({ ...data, sessions: [s, ...data.sessions], totalUrges: data.totalUrges + urge }); setPhoneModal(false); setScreen('home'); setRunning(false); setReflection(''); };
  const continueWork = () => { setPhoneModal(false); setKind('focus'); setDuration(25); setRemaining(25*60); setScreen('timer'); setRunning(true); };
  const beginUrge = () => { setRunning(false); setUrge(n => n + 1); setUrgeLeft(60); setScreen('urge'); };
  const urgeDecision = (keep: boolean) => { setScreen('timer'); if (keep) setRunning(true); else { setKind('break'); setRemaining(5*60); setDuration(5); setRunning(true); } };
  const demo = () => { const today = new Date(); const sample = [25,20,2,30,15].map((m,i)=>({ id:`demo-${i}`, task:['React project','Math practice','Started reading','Design notes','Language study'][i], minutes:m, date:new Date(today.getTime()-i*86400000).toISOString(), reflection:'One small step at a time.', away:i%3, urge:i%2, phoneDown:i%2===0 })); save({ sessions: sample, totalAway: 7, totalUrges: 3 }); };
  const todaySessions = data.sessions.filter(s => dayKey(new Date(s.date)) === dayKey(new Date()));
  const streak = (() => { const days = new Set(data.sessions.map(s=>dayKey(new Date(s.date)))); let n=0, d=new Date(); if(!days.has(dayKey(d))) d.setDate(d.getDate()-1); while(days.has(dayKey(d))){n++;d.setDate(d.getDate()-1);} return n; })();
  const week = Array.from({length:7},(_,i)=>{const d=new Date();d.setHours(0,0,0,0);d.setDate(d.getDate()-(6-i));return {date:d,mins:data.sessions.filter(s=>dayKey(new Date(s.date))===dayKey(d)).reduce((a,s)=>a+s.minutes,0)};});
  const install = async () => { if(installPrompt){await installPrompt.prompt();setInstallPrompt(null);} else alert('In your browser menu choose “Add to Home screen” or “Install app”.'); };

  return <div className="app-shell">
    <header className="topbar"><button className="brand" onClick={()=>setScreen('home')}><span className="brand-icon"><Heart size={18} fill="currentColor"/></span><span>focusbuddy<small>one little start</small></span></button><nav><button className={screen==='dashboard'?'nav-active':''} onClick={()=>setScreen('dashboard')}><Activity size={17}/> Progress</button><button className={screen==='settings'?'nav-active':''} onClick={()=>setScreen('settings')}><Settings size={17}/> Settings</button></nav></header>
    <main>
      {screen==='home' && <div className="home-layout"><section className="hero"><div className="eyebrow"><span className="dot"/> YOUR GENTLE RESET</div><h1>One small start<br/><em>changes the day.</em></h1><p className="lead">You don’t need to feel ready. Just give yourself two quiet minutes to begin.</p><button className="primary start-button" onClick={startForm}><span>Just 2 minutes</span><ChevronRight/></button><button className="text-link" onClick={()=>{setTaskInput(task);setScreen('setup');}}>Set a longer focus session <ArrowLeft size={15}/></button><div className="honesty"><Info size={17}/><span>FocusBuddy can notice when you leave this tab. It can’t block other apps on your phone.</span></div></section>
      <aside className="side-card"><div className="illustration"><div className="sun"/><div className="plant p1">✿</div><div className="plant p2">✦</div><div className="phone">◌</div><div className="book">▰</div></div><div className="side-copy"><div className="eyebrow">A NOTE FOR TODAY</div><p>“You don’t have to catch up on everything. Just begin with the next thing.”</p><span>Progress, with a little kindness.</span></div></aside>
      <section className="recent-card"><div className="section-heading"><div><div className="eyebrow">YOUR STORY</div><h2>Little by little</h2></div><button className="subtle" onClick={()=>setScreen('dashboard')}>See all <ChevronRight size={16}/></button></div>{data.sessions.length?data.sessions.slice(0,3).map(s=><div className="story-row" key={s.id}><span className="story-dot"/><strong>{s.minutes} min</strong><span>{s.reflection||s.task}</span><time>{dateLabel(s.date)}</time></div>):<p className="empty">Your first little win will show up here.</p>}</section></div>}
      {screen==='setup' && <section className="center-panel"><button className="back-link" onClick={()=>setScreen('home')}><ArrowLeft size={16}/> Back</button><div className="eyebrow">LET’S MAKE IT EASY</div><h1>What would you like<br/><em>to work on?</em></h1><label className="field-label" htmlFor="task">A small, clear task</label><input id="task" autoFocus maxLength={90} placeholder="e.g. Read the first chapter" value={taskInput} onChange={e=>setTaskInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&begin(2,'starter')}/><div className="duration-box"><span>Or choose a focus session</span><div className="duration-controls"><button onClick={()=>setDuration(Math.max(5,duration-5))}>−</button><strong>{duration} <small>min</small></strong><button onClick={()=>setDuration(Math.min(90,duration+5))}>+</button></div><div className="preset-row">{[15,25,45].map(n=><button className={duration===n?'selected':''} onClick={()=>setDuration(n)} key={n}>{n} min</button>)}</div></div><div className="start-options"><button className="primary" onClick={()=>begin(2,'starter')}>Just 2 minutes <ChevronRight size={18}/></button><button className="secondary" onClick={()=>begin(duration,'focus')}>Start {duration}-minute focus <ChevronRight size={18}/></button></div><p className="under-button">You can always pause or change your mind.</p></section>}
      {screen==='timer' && <section className="timer-panel"><div className="timer-top"><div className="eyebrow">{kind==='break'?'A LITTLE BREATHER':kind==='starter'?'YOUR TWO MINUTES':'FOCUS TIME'}</div><button className="subtle" onClick={()=>{setRunning(false);setScreen('home');}}><X size={16}/> End session</button></div><div className="timer-face"><svg viewBox="0 0 240 240" className="ring"><circle cx="120" cy="120" r="108"/><circle cx="120" cy="120" r="108" className="ring-progress" style={{strokeDashoffset:678*(1-remaining/(duration*60))}}/></svg><div className="time-readout"><strong>{fmt(remaining)}</strong><span>{kind==='break'?'break':'remaining'}</span></div></div><div className="task-chip"><span className="dot"/>{task}</div><div className="timer-actions"><button className="primary" onClick={()=>setRunning(!running)}>{running?<Pause size={18}/>:<Play size={18} fill="currentColor"/>}{running?'Pause':'Resume'}</button><button className="secondary" onClick={()=>{setRemaining(duration*60);setRunning(false);}}><RotateCcw size={17}/> Reset</button></div>{nudge&&<div className="nudge"><Sparkles size={18}/><div><p>“{nudge}”</p><small>{aiLabel}</small></div></div>}{kind!=='break'&&<><div className="phone-note"><Smartphone size={18}/><div><strong>Phone-down challenge 📱</strong><p>Put your phone somewhere a little harder to reach. Just create some distance.</p></div></div><button className="urge-button" onClick={beginUrge}>I want to scroll <span>Pause and ride the urge gently</span></button></>}<p className="away-note">You’ve left FocusBuddy {away} {away===1?'time':'times'}. Awareness is progress.</p></section>}
      {screen==='urge' && <section className="urge-panel"><div className="breath-orb"><span/></div><div className="eyebrow">A MOMENT FOR YOU</div><h1>You don’t have to fight<br/><em>the urge.</em></h1><p className="lead">Just wait 60 seconds before deciding. Breathe in, breathe out.</p><div className="urge-clock">{fmt(urgeLeft)}</div><div className="breathing">{urgeLeft>0?'Breathe in gently · breathe out slowly':'Still want to scroll?'}</div>{urgeLeft===0&&<div className="timer-actions"><button className="primary" onClick={()=>urgeDecision(true)}>Continue focusing</button><button className="secondary" onClick={()=>urgeDecision(false)}><Coffee size={17}/> Take a break</button></div>}<button className="text-link" onClick={()=>urgeDecision(true)}>I’m ready to go back</button></section>}
      {screen==='complete' && <section className="center-panel complete-panel"><div className="complete-icon"><Check/></div><div className="eyebrow">YOU SHOWED UP</div><h1>You started.<br/><em>That matters.</em></h1><p className="lead">What did you work on? A few words are plenty.</p><textarea maxLength={160} placeholder={task} value={reflection} onChange={e=>setReflection(e.target.value)}/><div className="phone-question"><Smartphone size={19}/><strong>Did you keep your phone away?</strong></div><div className="timer-actions"><button className="primary" onClick={()=>finish(true)}>Yep <Check size={16}/></button><button className="secondary" onClick={()=>finish(false)}>Not this time</button></div><button className="text-link" onClick={continueWork}>You started. Want to keep going? Keep going <ChevronRight size={15}/></button><button className="text-link" onClick={()=>finish()}>Take a break</button></section>}
      {screen==='dashboard' && <section className="dashboard"><div className="eyebrow">A LITTLE GOES A LONG WAY</div><h1>Your progress,<br/><em>your pace.</em></h1><div className="stats-grid"><div className="stat"><Flame/><strong>{streak}</strong><span>day streak</span></div><div className="stat"><Timer/><strong>{data.sessions.reduce((a,s)=>a+s.minutes,0)}</strong><span>focus minutes</span></div><div className="stat"><Check/><strong>{data.sessions.length}</strong><span>sessions</span></div><div className="stat"><Activity/><strong>{data.totalAway}</strong><span>tab leaves noticed</span></div><div className="stat"><Heart/><strong>{data.totalUrges}</strong><span>scroll pauses</span></div></div><div className="chart-card"><div className="section-heading"><div><div className="eyebrow">THE LAST SEVEN DAYS</div><h2>Showing up looks like this</h2></div><span className="unit">minutes</span></div><div className="chart">{week.map((d,i)=><div className="bar-col" key={i}><strong>{d.mins||''}</strong><div className="bar-track"><div className="bar" style={{height:`${Math.max(d.mins?8:0,Math.min(100,d.mins/60*100))}%`}}/></div><span>{d.date.toLocaleDateString(undefined,{weekday:'short'})}</span></div>)}</div>{streak===0&&<p className="fresh">Fresh start 🌱 Every day is a new chance to begin.</p>}</div><div className="history-card"><div className="section-heading"><div><div className="eyebrow">YOUR STORY</div><h2>Sessions & reflections</h2></div><History/></div>{data.sessions.length?data.sessions.map(s=><div className="story-row" key={s.id}><span className="story-dot"/><strong>{s.minutes} min</strong><span>{s.reflection||s.task}</span><time>{dateLabel(s.date)}</time></div>):<p className="empty">Your sessions will become a story of small starts.</p>}</div><div className="dashboard-foot">{todaySessions.length?`${todaySessions.length} little ${todaySessions.length===1?'start':'starts'} today. Nice work being here.`:'Today is a good day for a fresh start.'}</div></section>}
      {screen==='settings' && <section className="settings"><div className="eyebrow">MAKE IT YOURS</div><h1>Little settings,<br/><em>your way.</em></h1><div className="settings-card"><div className="setting-line"><div><strong>On-device AI nudges</strong><p>Optional Qwen model runs in your browser. First use downloads the model.</p></div><label className="switch"><input type="checkbox" checked={localStorage.getItem('fb-ai')==='on'} onChange={e=>{localStorage.setItem('fb-ai',e.target.checked?'on':'off');}}/><span/></label></div><div className="setting-line"><div><strong>AI availability</strong><p>WebGPU: {'gpu' in navigator?'available on this browser':'not detected — kind fallback nudges remain available'}</p></div></div><div className="setting-line"><div><strong>Install FocusBuddy</strong><p>Add it to your home screen for a quieter, app-like experience.</p></div><button className="secondary" onClick={install}><Smartphone size={16}/> Install</button></div><div className="setting-line"><div><strong>Try a demo</strong><p>Add sample sessions to explore the dashboard. You can clear everything below.</p></div><button className="secondary" onClick={demo}>Load demo data</button></div><button className="clear-button" onClick={()=>{if(confirm('Clear all FocusBuddy history from this device?')){save(EMPTY);}}}>Clear my local history</button></div><div className="privacy-note"><Heart size={17}/> Your focus history and reflections stay on this device. The optional AI model also runs locally; no reflection or task is sent to a server.</div><div className="about-card"><div className="eyebrow">WHY FOCUSBUDDY?</div><h2>A small tool for a real problem.</h2><p>My friend wants to study, but when it’s time to start, scrolling is always one tap away. I can’t stop him scrolling. But I can make starting his work easier.</p><button className="text-link" onClick={()=>setAbout(!about)}>{about?'Hide':'Read the story'} <ChevronRight size={16}/></button>{about&&<div className="about-text"><h3>The honest limitation</h3><p>A browser cannot reliably block other phone apps. FocusBuddy only counts when its tab becomes hidden.</p><h3>The approach</h3><p>Make starting easier, notice tab distractions, pause before scrolling, encourage a phone-down moment, and turn finished sessions into visible progress.</p><h3>Open innovation</h3><p>Qwen is open-weight and can be swapped. The AI layer is inspectable and customizable, local inference is possible, and developers can experiment without tying the whole product to a proprietary AI API. Local model files are downloaded from the configured model registry; use the standard fallback without downloading any AI model.</p></div>}</div></section>}
    </main>
    {phoneModal&&screen==='timer'&&kind!=='break'&&<div className="modal-backdrop"><div className="modal"><button className="modal-x" onClick={()=>setPhoneModal(false)}><X size={18}/></button><div className="eyebrow">PHONE-DOWN CHALLENGE 📱</div><h2>A little distance<br/>is plenty.</h2><p>Put your phone somewhere a little harder to reach. You don’t need perfect discipline. Just create some distance.</p><button className="primary full" onClick={()=>setPhoneModal(false)}>Got it, let’s begin <ChevronRight size={18}/></button></div></div>}
    <footer><span><Heart size={14} fill="currentColor"/> Your focus history and reflections stay on this device.</span><div><button onClick={installable?install:()=>setScreen('settings')}>Install app</button><button onClick={()=>setScreen('settings')}>Privacy & about</button></div></footer>
  </div>;
}
